language: scala
scala: 2.11.6
jdk:
- oraclejdk8
script: sbt clean coverage test && sbt coverageAggregate
after_success: sbt coveralls
env:
  global:
    secure: U9JES0PngtEiAq4xG9AJM/dA+PqeApx9X5KyLarIUcD8OC802cM75UyTHs3BfeZFZQD16rADacUE7MZnZca/LHLaUJgfwlvWwW4Qcy3goSyoFnI5ki3dKORICksJ1kaaWnU0dnTPRe7W2DGwfX06s2CNc90BBJZRwG0Du48hQQU=
