# dev compose
# extend from docker-compose-common.yml
geocoder:
  extends:
    file: docker-compose-common.yml
    service: geocoder
  links:
    - lines
    - points
    - parser

lines:
  extends:
    file: docker-compose-common.yml
    service: lines
  links: 
    - elasticsearch

points:
  extends:
    file: docker-compose-common.yml
    service: points
  links: 
    - elasticsearch

parser:
  extends:
    file: docker-compose-common.yml
    service: parser

# volumes allows for data to be loaded without being part of the container
loader:
  extends:
    file: docker-compose-common.yml
    service: loader
  links:
    - elasticsearch
  volumes:
    - ../grasshopper-loader/test/data:/usr/src/app/test/data/

# add port to make it viewable
elasticsearch:
  extends:
    file: docker-compose-common.yml
    service: elasticsearch
  ports:
    - "9200:9200"

# volume allows for refesh (easy front-end development)
ui:
  extends:
    file: docker-compose-common.yml
    service: ui
  links:
    - geocoder
  volumes:
    - ../grasshopper-ui/dist:/opt/grasshopper-ui/
